version: '3.7'

services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 12345678A@  
      POSTGRES_ROOT_PASSWORD: 12345678A@
    volumes:
      - postgres_db:/var/lib/postgresdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend-network 

  web:
    stdin_open: true
    tty: true
    container_name: api-sim
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 3333
    volumes:
      - ./:/opt/app
    depends_on:
      postgresql:
        condition: service_healthy 
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
    healthcheck:
      test: curl --fail backend:3030/health || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
    driver: bridge

volumes:
  postgres_db:
  